vscode:
  extensions:
    - dracula-theme.theme-dracula@2.22.3:c2qxutk2xT/UW8L9+9bW2g==
    - PKief.material-icon-theme@4.4.0:rUeW9VprKCFBXYTvg+AimA==
    - CoenraadS.bracket-pair-colorizer-2@0.2.0:R8flOpw1fEZe6KyMNNNqBQ==
    - naumovs.color-highlight@2.3.0:6nKORbxgnWjNaN6xACiaQQ==